# Install Dependencies

In [ ]:
#!pip install pycaret pandas shap

In [1]:
#Import libraries
import pandas as pd
from pycaret.classification import *

# Load Data

In [2]:
data = pd.read_csv('heart.csv')

In [3]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [4]:
data.dtypes

age            int64
sex            int64
cp             int64
trestbps       int64
chol           int64
fbs            int64
restecg        int64
thalach        int64
exang          int64
oldpeak      float64
slope          int64
ca             int64
thal           int64
condition      int64
dtype: object

# Train And Evaluate Model

In [5]:
cat_feature = ['sex','cp', 'fbs','exang', 'thal']

setup() function is from PyCaret, it initiates the ML experiments and setups the training pipeline.
There are number of parameters that can be set for the experiment within the function.

In [6]:
experiment = setup(data, target='condition', categorical_features=cat_feature)

In PyCaret, the compare_models() after running this command it comapre all the machine learning model and highlights the best suited model for your datast.

In this Case the Navie Bayes ML algorithms is best suited with Accuracy = 0.8445

In [7]:
best_model = compare_models()

# Testing The Model

In [8]:
predict_model(best_model, data.tail())

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition,prediction_label,prediction_score
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1,0,0.5042
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1,1,0.9628
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1,1,0.9994
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0,0,0.9995
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2,1,1,0.9886

# Saving The Model

In [9]:
save_model(best_model, model_name='Navie-Bayes')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=C:\Users\SWAROO~1\AppData\Local\Temp\joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['age', 'trestbps', 'chol',
                                              'restecg', 'thalach', 'oldpeak',
                                              'slope', 'ca'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'...
 dtype: int64}],
                                                                return_df=True,
                                                                verbose=0))),
                 ('onehot_encoding',
                  TransformerWrapper(exclude=None, include=['cp', 'thal'],
                                     transformer=OneHotEncoder(cols=['cp',
                                                                     'thal'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               return_df=True,
                                                               use_cat_names=True,
                                                               verbose=0))),
                 ('trained_model',
                  GaussianNB(priors=None, var_smoothing=1e-09))],
          verbose=False),
 'Navie-Bayes.pkl')